from rest_framework import serializers
from ..models.etudiant import Etudiant

class EtudiantSerializer(serializers.Serializer):
    id = serializers.CharField(read_only=True)
    username = serializers.CharField()
    email = serializers.EmailField()
    password = serializers.CharField(write_only=True)
    bac_type = serializers.CharField()
    session = serializers.CharField(required=False)

    
    # Moyennes
    mg_principale = serializers.FloatField(required=False)
    mg_controle = serializers.FloatField(required=False)
    mg = serializers.FloatField(required=False)
    ville = serializers.CharField(required=False)
    # Notes finales
    A = serializers.FloatField(required=False)
    PH = serializers.FloatField(required=False)
    HG = serializers.FloatField(required=False)
    F = serializers.FloatField(required=False)
    Ang = serializers.FloatField(required=False)
    M = serializers.FloatField(required=False)
    SP = serializers.FloatField(required=False)
    Info = serializers.FloatField(required=False)
    SVT = serializers.FloatField(required=False)
    Ec = serializers.FloatField(required=False)
    Ge = serializers.FloatField(required=False)
    TE = serializers.FloatField(required=False)
    Algo = serializers.FloatField(required=False)
    STI = serializers.FloatField(required=False)
    SB = serializers.FloatField(required=False)
    Sp_sport = serializers.FloatField(required=False)
    IT = serializers.FloatField(required=False)
    ESP = serializers.FloatField(required=False)
    All = serializers.FloatField(required=False)
    EP = serializers.FloatField(required=False)
    
    # Notes principales
    A_principale = serializers.FloatField(required=False)
    HG_principale = serializers.FloatField(required=False)
    F_principale = serializers.FloatField(required=False)
    Ang_principale = serializers.FloatField(required=False)
    M_principale = serializers.FloatField(required=False)
    SP_principale = serializers.FloatField(required=False)
    Sp_sport_principale = serializers.FloatField(required=False)
    SVT_principale = serializers.FloatField(required=False)
    Ge_principale = serializers.FloatField(required=False)
    Ec_principale = serializers.FloatField(required=False)
    TE_principale = serializers.FloatField(required=False)
    Algo_principale = serializers.FloatField(required=False)
    STI_principale = serializers.FloatField(required=False)
    Info_principale = serializers.FloatField(required=False)
    SB_principale = serializers.FloatField(required=False)
    EP_principale = serializers.FloatField(required=False)
    
    # Notes de contrôle
    A_controle = serializers.FloatField(required=False)
    HG_controle = serializers.FloatField(required=False)
    F_controle = serializers.FloatField(required=False)
    Ang_controle = serializers.FloatField(required=False)
    M_controle = serializers.FloatField(required=False)
    SP_controle = serializers.FloatField(required=False)
    Sp_sport_controle = serializers.FloatField(required=False)
    SVT_controle = serializers.FloatField(required=False)
    Ge_controle = serializers.FloatField(required=False)
    Ec_controle = serializers.FloatField(required=False)
    TE_controle = serializers.FloatField(required=False)
    Algo_controle = serializers.FloatField(required=False)
    STI_controle = serializers.FloatField(required=False)
    Info_controle = serializers.FloatField(required=False)
    SB_controle = serializers.FloatField(required=False)
    EP_controle = serializers.FloatField(required=False)
    
    fg = serializers.FloatField(read_only=True)
    score = serializers.FloatField(required=False)